package com.jerboa.ui.theme

import androidx.compose.material.ContentAlpha
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

// Old colors
val Blue200 = Color(0xFF3498db)
val Blue500 = Color(0xFF21608B)
val Blue700 = Color(0xFF1A4A69)
val Green200 = Color(0xFF00bc8c)
val Green500 = Color(0xFF018564)
val Green700 = Color(0xFF004634)
val Yellow40 = Color(0xff7d5700)
val Pink200 = Color(0xffFF00FF)
val Pink700 = Color(0xFFAF0AAF)

val DarkSurfaceBlue = Color(0xFF0e1d29)
val BlackSurface = Color(0xFF000000)

val md_theme_light_primary = Color(0xFF9A4057)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD9DF)
val md_theme_light_onPrimaryContainer = Color(0xFF3F0016)
val md_theme_light_secondary = Color(0xFF006397)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001D31)
val md_theme_light_tertiary = Color(0xFF7A5732)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCBC)
val md_theme_light_onTertiaryContainer = Color(0xFF2C1700)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1B)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A1B)
val md_theme_light_surfaceVariant = Color(0xFFF3DDE0)
val md_theme_light_onSurfaceVariant = Color(0xFF524345)
val md_theme_light_outline = Color(0xFF847375)
val md_theme_light_inverseOnSurface = Color(0xFFFAEEEE)
val md_theme_light_inverseSurface = Color(0xFF362F30)
val md_theme_light_inversePrimary = Color(0xFFFFB1C0)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF9A4057)
val md_theme_light_outlineVariant = Color(0xFFD6C2C4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB1C0)
val md_theme_dark_onPrimary = Color(0xFF5F112A)
val md_theme_dark_primaryContainer = Color(0xFF7C2940)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9DF)
val md_theme_dark_secondary = Color(0xFF92CCFF)
val md_theme_dark_onSecondary = Color(0xFF003351)
val md_theme_dark_secondaryContainer = Color(0xFF004B73)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_tertiary = Color(0xFFECBE90)
val md_theme_dark_onTertiary = Color(0xFF462A08)
val md_theme_dark_tertiaryContainer = Color(0xFF5F401D)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCBC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A1B)
val md_theme_dark_onBackground = Color(0xFFECE0E0)
val md_theme_dark_surface = Color(0xFF201A1B)
val md_theme_dark_onSurface = Color(0xFFECE0E0)
val md_theme_dark_surfaceVariant = Color(0xFF524345)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C2C4)
val md_theme_dark_outline = Color(0xFF9F8C8F)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1B)
val md_theme_dark_inverseSurface = Color(0xFFECE0E0)
val md_theme_dark_inversePrimary = Color(0xFF9A4057)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB1C0)
val md_theme_dark_outlineVariant = Color(0xFF524345)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFFFFC0CB)

val Color.muted @Composable get() = this.copy(alpha = ContentAlpha.medium)
