pipeline:
  check_formatting:
    image: cimg/android:2023.05
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew lintKotlin

  prettier_markdown_check:
    image: tmknom/prettier
    commands:
      - prettier -c *.md

  build_project:
    image: cimg/android:2023.05
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew assembleDebug

  notify_on_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'CI build failed: ${CI_BUILD_LINK}' ntfy.sh/jerboa_ci"
    when:
      status: [failure]
