variables:
  - &android_image "cimg/android:2024.11"

steps:
  prettier_markdown_check:
    image: tmknom/prettier
    commands:
      - prettier -c "*.md" "*.yml"
    when:
      - event: pull_request

  check_formatting:
    image: *android_image
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew lintKotlin
    environment:
      GRADLE_USER_HOME: ".gradle"
    when:
      - event: pull_request

  build_project:
    image: *android_image
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew assembleRelease
    environment:
      GRADLE_USER_HOME: ".gradle"
    when:
      - event: pull_request

  run_tests:
    image: *android_image
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew testDebug
    environment:
      GRADLE_USER_HOME: ".gradle"
    when:
      - event: pull_request

  notify:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Jerboa build ${CI_PIPELINE_STATUS}: ${CI_PIPELINE_URL}' ntfy.sh/jerboa_ci"
    when:
      - event: pull_request
        status: [failure, success]
