package com.jerboa.datatypes.types

data class CreateSite(
    var name: String,
    var sidebar: String? = null,
    var description: String? = null,
    var icon: String? = null,
    var banner: String? = null,
    var enable_downvotes: Boolean? = null,
    var enable_nsfw: Boolean? = null,
    var community_creation_admin_only: Boolean? = null,
    var require_email_verification: Boolean? = null,
    var application_question: String? = null,
    var private_instance: Boolean? = null,
    var default_theme: String? = null,
    var default_post_listing_type: ListingType? /* "All" | "Local" | "Subscribed" */ = null,
    var legal_information: String? = null,
    var application_email_admins: Boolean? = null,
    var hide_modlog_mod_names: Boolean? = null,
    var discussion_languages: Array<LanguageId>? = null,
    var slur_filter_regex: String? = null,
    var actor_name_max_length: Int? = null,
    var rate_limit_message: Int? = null,
    var rate_limit_message_per_second: Int? = null,
    var rate_limit_post: Int? = null,
    var rate_limit_post_per_second: Int? = null,
    var rate_limit_register: Int? = null,
    var rate_limit_register_per_second: Int? = null,
    var rate_limit_image: Int? = null,
    var rate_limit_image_per_second: Int? = null,
    var rate_limit_comment: Int? = null,
    var rate_limit_comment_per_second: Int? = null,
    var rate_limit_search: Int? = null,
    var rate_limit_search_per_second: Int? = null,
    var federation_enabled: Boolean? = null,
    var federation_debug: Boolean? = null,
    var federation_worker_count: Int? = null,
    var captcha_enabled: Boolean? = null,
    var captcha_difficulty: String? = null,
    var allowed_instances: Array<String>? = null,
    var blocked_instances: Array<String>? = null,
    var taglines: Array<String>? = null,
    var registration_mode: RegistrationMode? /* "Closed" | "RequireApplication" | "Open" */ = null,
    var auth: String,
)