package com.jerboa.datatypes.types

data class LocalSite(
    var id: LocalSiteId,
    var site_id: SiteId,
    var site_setup: Boolean,
    var enable_downvotes: Boolean,
    var enable_nsfw: Boolean,
    var community_creation_admin_only: Boolean,
    var require_email_verification: Boolean,
    var application_question: String? = null,
    var private_instance: Boolean,
    var default_theme: String,
    var default_post_listing_type: ListingType /* "All" | "Local" | "Subscribed" */,
    var legal_information: String? = null,
    var hide_modlog_mod_names: Boolean,
    var application_email_admins: Boolean,
    var slur_filter_regex: String? = null,
    var actor_name_max_length: Int,
    var federation_enabled: Boolean,
    var federation_debug: Boolean,
    var federation_worker_count: Int,
    var captcha_enabled: Boolean,
    var captcha_difficulty: String,
    var published: String,
    var updated: String? = null,
    var registration_mode: RegistrationMode /* "Closed" | "RequireApplication" | "Open" */,
    var reports_email_admins: Boolean,
)