/***********************************************
 *        WARNING: AUTO-GENERATED FILE         *
 ***********************************************/

// The following file is automatically generated by the script "update_instance_gradle.kts".
// Caution: Manual modifications to this file may be overwritten without notice.
// It is recommended to make changes to the code section responsible for the generation.

// Date of Auto-generation: 2024-06-12

package com.jerboa

val DEFAULT_LEMMY_INSTANCES = setOf(
    "lemmy.world", // 18236 monthly users
    "lemm.ee", // 3404 monthly users
    "lemmy.ml", // 2493 monthly users
    "sh.itjust.works", // 2489 monthly users
    "hexbear.net", // 1699 monthly users
    "feddit.de", // 1567 monthly users
    "lemmy.ca", // 1407 monthly users
    "programming.dev", // 1146 monthly users
    "lemmy.dbzer0.com", // 1119 monthly users
    "discuss.tchncs.de", // 938 monthly users
    "lemmy.blahaj.zone", // 914 monthly users
    "lemmygrad.ml", // 582 monthly users
    "sopuli.xyz", // 572 monthly users
    "lemmy.sdf.org", // 548 monthly users
    "lemmy.zip", // 513 monthly users
    "beehaw.org", // 420 monthly users
    "aussie.zone", // 376 monthly users
    "feddit.nl", // 371 monthly users
    "infosec.pub", // 353 monthly users
    "midwest.social", // 345 monthly users
    "reddthat.com", // 314 monthly users
    "feddit.uk", // 301 monthly users
    "slrpnk.net", // 297 monthly users
    "lemmy.one", // 278 monthly users
    "jlai.lu", // 246 monthly users
    "pawb.social", // 229 monthly users
    "lemmy.today", // 212 monthly users
    "startrek.website", // 211 monthly users
    "feddit.it", // 207 monthly users
    "ttrpg.network", // 174 monthly users
    "mander.xyz", // 164 monthly users
    "lemmings.world", // 157 monthly users
    "lemdro.id", // 148 monthly users
    "lemmy.eco.br", // 147 monthly users
    "ani.social", // 133 monthly users
    "szmer.info", // 121 monthly users
    "lemy.lol", // 118 monthly users
    "lemmy.nz", // 117 monthly users
    "monero.town", // 115 monthly users
    "burggit.moe", // 102 monthly users
    "discuss.online", // 99 monthly users
    "feddit.dk", // 99 monthly users
    "awful.systems", // 94 monthly users
    "thelemmy.club", // 76 monthly users
    "feddit.nu", // 67 monthly users
    "yiffit.net", // 67 monthly users
    "leminal.space", // 59 monthly users
    "lemmy.wtf", // 53 monthly users
)
