package com.jerboa

val DEFAULT_LEMMY_INSTANCES = setOf(
    "lemmy.world", // 27779 monthly users
    "lemmy.ml", // 4367 monthly users
    "beehaw.org", // 3512 monthly users
    "lemm.ee", // 3184 monthly users
    "sh.itjust.works", // 3178 monthly users
    "feddit.de", // 2968 monthly users
    "lemmy.fmhy.ml", // 1680 monthly users
    "lemmy.ca", // 1605 monthly users
    "www.hexbear.net", // 1562 monthly users
    "programming.dev", // 1265 monthly users
    "lemmy.dbzer0.com", // 1138 monthly users
    "lemmy.blahaj.zone", // 1090 monthly users
    "lemmy.one", // 1003 monthly users
    "vlemmy.net", // 919 monthly users
    "lemmy.sdf.org", // 861 monthly users
    "discuss.tchncs.de", // 853 monthly users
    "lemmygrad.ml", // 712 monthly users
    "sopuli.xyz", // 702 monthly users
    "reddthat.com", // 583 monthly users
    "aussie.zone", // 578 monthly users
    "feddit.uk", // 533 monthly users
    "feddit.nl", // 488 monthly users
    "midwest.social", // 472 monthly users
    "infosec.pub", // 402 monthly users
    "feddit.it", // 347 monthly users
    "ttrpg.network", // 347 monthly users
    "pawb.social", // 323 monthly users
    "lemmy.zip", // 313 monthly users
    "startrek.website", // 307 monthly users
    "burggit.moe", // 245 monthly users
    "slrpnk.net", // 237 monthly users
    "mander.xyz", // 219 monthly users
    "lemmy.eco.br", // 215 monthly users
    "lemmy.nz", // 185 monthly users
    "dormi.zone", // 178 monthly users
    "exploding-heads.com", // 172 monthly users
    "delraymisfitsboard.com", // 158 monthly users
    "monyet.cc", // 156 monthly users
    "feddit.dk", // 151 monthly users
    "lemmy.pt", // 138 monthly users
    "szmer.info", // 131 monthly users
    "yiffit.net", // 117 monthly users
    "geddit.social", // 106 monthly users
    "waveform.social", // 102 monthly users
    "discuss.online", // 92 monthly users
    "monero.town", // 89 monthly users
    "feddit.cl", // 89 monthly users
    "iusearchlinux.fyi", // 86 monthly users
    "dataterm.digital", // 86 monthly users
    "lemmy.whynotdrs.org", // 80 monthly users
    "feddit.ch", // 80 monthly users
    "enterprise.lemmy.ml", // 79 monthly users
    "lemmy.run", // 77 monthly users
    "jlai.lu", // 77 monthly users
    "pornlemmy.com", // 76 monthly users
    "lemdro.id", // 76 monthly users
    "lemmyrs.org", // 74 monthly users
    "latte.isnot.coffee", // 70 monthly users
    "feddit.nu", // 66 monthly users
    "lemmy.film", // 65 monthly users
    "bakchodi.org", // 53 monthly users
    "mujico.org", // 53 monthly users
    "lemmy.studio", // 50 monthly users
)
